var emmet = require('emmet')
var EmmetEditor = require('./EmmetEditor').EmmetEditor
require('emmet/bundles/snippets')
require('emmet/bundles/caniuse')

var scriptName = $.NSProcessInfo.processInfo.arguments.lastObject.lastPathComponent.js

$.NSLog(scriptName)

var app = Application('CotEditor')
app.includeStandardAdditions = true
var doc = app.documents[0]
var editor = new EmmetEditor(doc, app)

if (scriptName.match(/^Expand Abbreviation/))
  emmet.run('expand_abbreviation', editor)
else if (scriptName.match(/^Balance \(outward\)/))
  emmet.run('balance_outward', editor)
//else if (scriptName.match(/^Balance \(inward\)/))
//  emmet.run('balance_inward', editor)
else if (scriptName.match(/^HTML Go To Matching Tag Pair/))
  emmet.run('matching_pair', editor)
else if (scriptName.match(/^Wrap With Abbreviation/))
  emmet.run('wrap_with_abbreviation', editor)
else if (scriptName.match(/^Next Edit Point/))
  emmet.run('next_edit_point', editor)
else if (scriptName.match(/^Previous Edit Point/))
  emmet.run('prev_edit_point', editor)
else if (scriptName.match(/^Select Next Item/))
  emmet.run('select_next_item', editor)
else if (scriptName.match(/^Select Previous Item/))
  emmet.run('select_previous_item', editor)
else if (scriptName.match(/^Toggle Comment/))
  emmet.run('toggle_comment', editor)
else if (scriptName.match(/^HTML Split Join Tag Declaration/))
  emmet.run('split_join_tag', editor)
else if (scriptName.match(/^HTML Remove Tag/))
  emmet.run('remove_tag', editor)
else if (scriptName.match(/^Merge Lines/))
  emmet.run('merge_lines', editor)
else if (scriptName.match(/^Update Image Size/))
  emmet.run('update_image_size', editor)
else if (scriptName.match(/^Numbers Evaluate Math Expression/))
  emmet.run('evaluate_math_expression', editor)
else if (scriptName.match(/^Numbers Increment number by 10/))
  emmet.run('increment_number_by_10', editor)
else if (scriptName.match(/^Numbers Decrement number by 10/))
  emmet.run('decrement_number_by_10', editor)
else if (scriptName.match(/^Numbers Increment number by 1/))
  emmet.run('increment_number_by_1', editor)
else if (scriptName.match(/^Numbers Decrement number by 1/))
  emmet.run('decrement_number_by_1', editor)
else if (scriptName.match(/^Numbers Increment number by 01/))
  emmet.run('increment_number_by_01', editor)
else if (scriptName.match(/^Numbers Decrement number by 01/))
  emmet.run('decrement_number_by_01', editor)
else if (scriptName.match(/^CSS Reflect Value/))
  emmet.run('reflect_css_value', editor)
else if (scriptName.match(/^Encode Decode data URL image/))
  emmet.run('encode_decode_data_url', editor)
